version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm install
    - task: ecma:config

  check:
    - task: ecma:check
  fix:
    - task: ecma:fix
  build:
    - task: ecma:lib-build

  doc:
    - task: ecma:doc-build
  dev-doc:
    - task: ecma:doc-dev

  upgrade:
    - >
      pnpm up @pistonite/pure mono-dev
      @types/react i18next react-i18next
      @fluentui/react-components @fluentui/react-icons
    - pnpm dedupe
    - pnpm dedupe --check
    - task: install

  publish:
    - rm -rf dist
    - task: install
    - task: check
    - task: build
    - task: doc
    - task: ecma:publish
