version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm install
    - task: ecma:config
  upgrade:
    - task: setup
    - pnpm dedupe
    - pnpm dedupe --check
    - task: install
  check:
    - task: ecma:check
  fix:
    - task: ecma:fix
  build:
    - task: ecma:lib-build

  doc:
    - task: ecma:doc
  dev-doc:
    - task: ecma:doc-dev

  upgrade:
    - pnpm up @pistonite/pure mono-dev @types/react
    - pnpm dedupe
    - pnpm dedupe --check
    - task: setup




